spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://154.8.211.55:3306/summer?useSSL=false
    username: root
    password: ljf112233
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  resources:
    static-locations: file:C:/Backend/upload
server:
  port: 8081

